<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit7a6b148d3af50022c36908bf7af2ef0a
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('MatrixAddons\DocumentEngine\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \MatrixAddons\DocumentEngine\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit7a6b148d3af50022c36908bf7af2ef0a', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \MatrixAddons\DocumentEngine\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit7a6b148d3af50022c36908bf7af2ef0a', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\MatrixAddons\DocumentEngine\Vendor\Composer\Autoload\ComposerStaticInit7a6b148d3af50022c36908bf7af2ef0a::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \MatrixAddons\DocumentEngine\Vendor\Composer\Autoload\ComposerStaticInit7a6b148d3af50022c36908bf7af2ef0a::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
